"""empty message

Revision ID: 5203dac34ad4
Revises: 
Create Date: 2026-01-06 01:16:24.780426

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5203dac34ad4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dosen',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('nidn', sa.String(length=30), nullable=False),
    sa.Column('nama', sa.String(length=50), nullable=False),
    sa.Column('phone', sa.String(length=13), nullable=False),
    sa.Column('alamat', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('kelas',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('nama_mk', sa.String(length=100), nullable=False),
    sa.Column('kode_mk', sa.String(length=20), nullable=False),
    sa.Column('sks', sa.Integer(), nullable=False),
    sa.Column('semester', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kode_mk')
    )
    op.create_table('ruangan',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('nama_ruang', sa.String(length=50), nullable=False),
    sa.Column('kapasitas', sa.Integer(), nullable=False),
    sa.Column('lokasi', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('jadwal',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('hari', sa.String(length=20), nullable=False),
    sa.Column('jam_mulai', sa.Time(), nullable=False),
    sa.Column('jam_selesai', sa.Time(), nullable=False),
    sa.Column('dosen_id', sa.BigInteger(), nullable=False),
    sa.Column('kelas_id', sa.BigInteger(), nullable=False),
    sa.Column('ruangan_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['dosen_id'], ['dosen.id'], ),
    sa.ForeignKeyConstraint(['kelas_id'], ['kelas.id'], ),
    sa.ForeignKeyConstraint(['ruangan_id'], ['ruangan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('jadwal')
    op.drop_table('ruangan')
    op.drop_table('kelas')
    op.drop_table('dosen')
    # ### end Alembic commands ###
